CREATE TABLE `client` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(150) CHARACTER SET utf8mb4 DEFAULT NULL,
  `RegistryDate` date DEFAULT NULL,
  `DateOfBirth` date DEFAULT NULL,
  `Address` varchar(150) CHARACTER SET utf8mb4 DEFAULT NULL,
  `Neighborhood` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `City` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `State` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `PostalCode` varchar(20) CHARACTER SET utf8mb4 DEFAULT NULL,
  `Cpf` varchar(20) CHARACTER SET utf8mb4 DEFAULT NULL,
  `Seller` varchar(30) CHARACTER SET utf8mb4 DEFAULT NULL,
  `JobName` varchar(60) CHARACTER SET utf8mb4 DEFAULT NULL,
  `Occupation` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `PlaceOfBirth` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `Spouse` varchar(150) CHARACTER SET utf8mb4 DEFAULT NULL,
  `Note` longtext CHARACTER SET utf8mb4,
  `Phone1` varchar(20) CHARACTER SET utf8mb4 DEFAULT NULL,
  `Phone2` varchar(20) CHARACTER SET utf8mb4 DEFAULT NULL,
  `AddressNumber` varchar(20) CHARACTER SET utf8mb4 DEFAULT NULL,
  `Rg` varchar(20) CHARACTER SET utf8mb4 DEFAULT NULL,
  `Complement` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,
  `AdmissionDate` date DEFAULT NULL,
  `CivilStatus` tinyint(4) NOT NULL,
  `FatherName` varchar(150) CHARACTER SET utf8mb4 DEFAULT NULL,
  `MotherName` varchar(150) CHARACTER SET utf8mb4 DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

